services:
  api:
    build: .
    image: tender-api:dev
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  postgres:
    ports:
      - '5432:5432'
  redis:
    ports:
      - '6379:6379'
