"""init

Revision ID: 476ebbdfa75c
Revises: 
Create Date: 2026-04-27 17:05:42.224001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '476ebbdfa75c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictionary_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('html_origin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tender_id'), 'documents', ['tender_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('scoring_formula', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value_good_name', sa.String(length=255), nullable=True),
    sa.Column('value_good_score', sa.Numeric(), nullable=True),
    sa.Column('value_bad_name', sa.String(length=255), nullable=True),
    sa.Column('value_bad_score', sa.Numeric(), nullable=True),
    sa.Column('promt_snippet', sa.String(), nullable=True),
    sa.Column('promt_chouser', sa.String(), nullable=True),
    sa.Column('promt_valuation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_template_id'), 'metrics', ['template_id'], unique=False)
    op.create_table('tender2template_favorites',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id', 'template_id')
    )
    op.create_table('template2document2metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('metric_start', sa.Integer(), nullable=True),
    sa.Column('metric_end', sa.Integer(), nullable=True),
    sa.Column('is_chosen', sa.Boolean(), nullable=True),
    sa.Column('value_name', sa.String(length=255), nullable=True),
    sa.Column('value_score', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'document_id', 'metric_id', name='uq_template_document_metric')
    )
    op.create_index(op.f('ix_template2document2metrics_document_id'), 'template2document2metrics', ['document_id'], unique=False)
    op.create_index(op.f('ix_template2document2metrics_metric_id'), 'template2document2metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_template2document2metrics_template_id'), 'template2document2metrics', ['template_id'], unique=False)
    op.create_table('tender2template2metric',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id', 'template_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender2template2metric')
    op.drop_index(op.f('ix_template2document2metrics_template_id'), table_name='template2document2metrics')
    op.drop_index(op.f('ix_template2document2metrics_metric_id'), table_name='template2document2metrics')
    op.drop_index(op.f('ix_template2document2metrics_document_id'), table_name='template2document2metrics')
    op.drop_table('template2document2metrics')
    op.drop_table('tender2template_favorites')
    op.drop_index(op.f('ix_metrics_template_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_templates_user_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_documents_tender_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenders')
    op.drop_table('dictionary_regions')
    op.drop_table('dictionary_platforms')
    # ### end Alembic commands ###
